project:
  type: website
  output-dir: docs
  resources:
    - "lecture-scripts/*"
    - "assignments"
    - "lecture-notes/*.ipynb"
  

website:
  body-footer: |
    <br> <br> <span style="color:grey;">&#169; Phil Chodrow, 2024</span>
  navbar:
    collapse-level: 1	
    style: "docked"
    title: |
      <b>Machine Learning</b> | CSCI 0451 S24
    left:
      - text: "Syllabus"
        file: index.qmd
      - schedule.qmd
      - assignments.qmd
      - project.qmd
  favicon: assets/icons/favicon.png

bibliography: refs.bib

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    number-depth: 0
    reference-location: margin
    callout-icon: false;
    callout-appearance: simple
    title-block-style: none

jupyter: conda-env-ml-0451-py

execute: 
  cache: true



