---
title: Expectations for Blog Posts
---


The following expectations apply to all submitted blog posts in CSCI 0451. 



## Writing

Blog posts are ***computational essays***. 

- Please write in thoughtfully composed English paragraphs. 
- You should **explain all code** displayed in your blog post, in such a way that your reader can understand what you are doing. 
    - A corollary is that you should break large code blocks up into smaller ones so that you can explain your approach. 
- Please make sure that your writing also responds to all prompts in the body of the blog post assignment. 

In this course, writing is a fundamental part of the learning process. Blog posts that have fully correct technical solutions but which are missing major written components will generally receive feedback of an M (which means "I think you could learn more on this assignment") rather than an E. 

**Tip**: Quarto offers [some neat functionality](https://quarto.org/docs/authoring/code-annotation.html) for marking up your code. Code comments can also be helpful, but do not replace text. 

## Code

Your code should be careful, concise, efficient Python. 

- Unless otherwise stated by the prompt, all your code can be included in your blog post itself (it is not necessary to create a separate module). 
- Whenever possible, `for`-loops should be minimized in favor of efficient vectorized operations in `numpy` and `pandas`. 

## Computational Outputs

- All plots must have labeled axes and legends when appropriate. 
- Use of [captions](https://quarto.org/docs/authoring/figures.html#computations) and [cross-references](https://quarto.org/docs/authoring/figures.html#cross-references) is encouraged. 
- When showing a visualization, every aspect of that visualiation should be discussed in the accompanying text. If an aspect of a visualization is not sufficiently important to include in your text, please remove it! 

## Text Formatting

- Mathematical content should be typeset using Quarto's [included MathJax syntax](https://quarto.org/docs/authoring/markdown-basics.html#equations). "alpha x y" is not appropriately typeset; instead, typing `$\alpha \times y$` produces the mathematics $\alpha \times y$. 
- All code should be in code blocks (Quarto will usually take care of this for you). Inline code can be rendered `like this.` 
