---
title: "Ideas for Goal-Setting"
date: 2024-02-12
author: Phil
type: "extra"
---

*If you're not sure what goals you might want to set for yourself when [setting your goals for the course](goal-setting.ipynb), here are a few ideas to help you get started. Don't limit yourself to just these ideas! They are just here to show you some possibilities and get your creative juices flowing.* ***Note that these are not requirements*** *and you do not have to do all of these in order to demonstrate learning in the course.*

## Blog Posts 

- *Submit a blog post in most weeks during the semester.*
- *Submit the first draft of no more than two blog posts after the "best-by" date.*
- *Revise at least five blog posts to the "No Revisions Suggested" level.*
- *Go above and beyond in at least two blog posts by implementing more complex algorithms, discussing more advanced theory, or performing experiments significantly beyond what is requested.*
- *Propose and complete a blog post on a topic not covered in lecture, especially one related to your areas of focused interest.*
- *Propose and complete an additional blog post on a topic related to algorithmic bias and social responsibility.*

## Course Presence  

- *Complete all core readings prior to each class periods.*
- *Complete the optional readings that correspond to my areas of specialization.*
- *"Pass" at most once when asked to lead the warmup activity for my group.*
- *Ask questions or make suggestions for the warmup presenter in most weeks.*
- *Propose questions ahead of time for our guest speaker.*
- *Organize a study group outside of class time to work on blog posts or other course work.*
- *Attend a study group outside of class time.*
- *Frequently attend Peer Help or Student Hours (after preparing questions and working examples).* 
- *Regularly post questions or answers on the course Slack workspace.*

## Project

- *Submit all project milestones (proposal, progress report, etc) on time.* 
- *Set regular time each week to work with project partners.*
- *Communicate with my group in a clear and timely manner.*
- *Implement algorithms or write automated checks of algorithms written by teammates.*
- *Draft designated sections of the project report.*
- *Revise sections of the project report in response to feedback.*
- *Lead creation of the final project presentation.*
- *Take the lead in delivering part of the final project presentation.*
- *Take the lead in checking project figures for accuracy and clear labeling.*